### ISSUE TITLE
Support for WS2812 LED

### ISSUE THREAD

**Issue by lazyzero** [fishpepper/OpenSky#1]
Hi,

it is more a feature request. Is it possible to have WS2812 LED instead of the APA?

Best Christian

**Comment by fishpepper** [comment]
the apa102s are much nicer! ws2812 use ~490Hz PWM frequency. If you fly this on a quacopter you get irritated by this. At least i do, i find it really annoying.
The APA102 leds use 16 (or 19?) kHz (!) as pwm frequency when driven properly. Thats way better :)

The protocol is also nicer, its not timing sensitive at all. you can clock out data at ANY rate you want
