### ISSUE TITLE
bind settings not stored (?) on d4r

### ISSUE THREAD

**Issue by fishpepper** [fishpepper/OpenSky#10]
there are some reports on the d4r about lost/not stored bind settings,
see https://www.rcgroups.com/forums/showthread.php?2735304-OpenSky-opensource-firmware-for-FrSky-D4R-ii-and-VD5M/page12

It seems like the rx does not store the bind settings for you?! Could you connect an ftdi rx pin or a spare fc rx pin (for uart3 e.g. use serialpassthrough 2 115200) and post the log during bind and 
one log for connecting after bind

**Comment by s3vo** [comment]
More info is here on my post on rcgroups: 
[https://www.rcgroups.com/forums/showpost.php?p=36570934&postcount=184](url)
here is a log from debug on D4R-II: 
`-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
### OpenSky - BUILD_TARGET - (c) by github.com/fishpepper ###
uart: init done
wdt: init
timeout: init
storage: init
hal_storage: freeing i2c bus with clock train
hal_storage: i2c free again
storage: reading
hal_storage: i2c read_buffer(0x0000, ..., 51)
hal_storage: reading 51bytes: 01 5A C9 01 88 24 AB 47 CE 6A 06 8D 29 B0 4C D3 6F 0B 92 2E B5 51 D8 74 10 97 33 BA 56 DD 79 15 9C 38 BF 5B E2 7E 1A A1 3D C4 60 E7 83 1F A6 42 C9 65 00 . done.
hal_storage: read done
storage: loaded hoptable[] = 01 88 24 AB 47 CE 6A 06 8D 29 B0 4C D3 6F 0B 92 2E B5 51 D8 74 10 97 33 BA 56 DD 79 15 9C 38 BF 5B E2 7E 1A A1 3D C4 60 E7 83 1F A6 42 C9 65 
frsky: init
cc25xx: init
frsky: cc25xx partnum 0x80 version 0x03
frsky: got valid part and version info
frsky: configure
frsky: configure done
frsky: BIND jumper set = YES -> binding
frsky: do bind
frsky: autotune
frsky: entering bind loop`

**Comment by Zebble** [comment]
This seems to be fixed.  Haven't had an issue with powering off and on after binding...

**Comment by fishpepper** [comment]
fixed by  		68c6e34
