### ISSUE TITLE
make bootloader failing under windows

### ISSUE THREAD

**Issue by Linjieqiang** [fishpepper/OpenSky#8]
![image](https://cloud.githubusercontent.com/assets/10217966/20607515/034ec436-b2b4-11e6-9236-fe8d8ca10c27.png)

I had a try to build your code,but it didn't work.I love your project for USKY.It was nice.Thanks.

**Comment by fishpepper** [comment]
something with the makefile seems to be broken under windows
i think its complaining about the path with the (x86) in your path
no idea why this happens under windows :-\

**Comment by Linjieqiang** [comment]
Can you provide me a newer hex for USKY ? I had no idea about this problem.

**Comment by fishpepper** [comment]
Could you try to replace $(MAKE) with make in arch/cc251x/Makefile.arch and try again?

**Comment by Linjieqiang** [comment]
I pull your newer code but error existed.My system is windows7 64bit.
![image](https://cloud.githubusercontent.com/assets/10217966/20705689/ea263260-b65e-11e6-998a-88a2280a44fb.png)
![image](https://cloud.githubusercontent.com/assets/10217966/20705706/00e3b432-b65f-11e6-9f1b-b1180fabe8e6.png)

**Comment by andymac4182** [comment]
I would check out using something like docker to do the build. The error messages talk about cygwin being the wrong version. Here is the one from betaflight https://github.com/mikeller/docker-betaflight-build

**Comment by Linjieqiang** [comment]
OK.@andymac4182 I will have a try. Thanks for your advise.

**Comment by Linjieqiang** [comment]
I bought a macbook pro computer and I will try again on it so this issue will be closed.Thanks.
